# Site settings
title: "Monochrome Collective"
email: "contactus@monochrome-collective.com"
phone: "+44 798 459 1105"
description: "Monochrome Collective, Pop Up Store in  Camden Collective, London"
baseurl: ""
url: "http://www.monochrome-collective.com"

collections:
  designers:
    output: "true"

# Build settings
markdown: "kramdown"
permalink: "pretty"
