# Site settings
title: "Monochrome Collective"
email: "your-email@domain.com"
description: "Monochrome Collective, Pop Up Store in  Camden Collective, London"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
